spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/company_system
    username: root
    password: hyeongwoo0!
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm
  expiration: 86400000

