spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/company_system
    username: root
    password: hyeongwoo0!
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8083
  servlet:
    context-path: /api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  secret: mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm
  expiration: 86400000

